BEGIN;

-- 확장 설치
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS vector;

-- users
CREATE TABLE IF NOT EXISTS users (
  user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username   VARCHAR(20)  NOT NULL UNIQUE,
  password   VARCHAR(255) NOT NULL,
  name       VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- chat_room
CREATE TABLE IF NOT EXISTS chat_room (
  chat_room_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id     BIGINT REFERENCES users(user_id),
  title        VARCHAR(255),
  created_at   TIMESTAMPTZ DEFAULT now(),
  updated_at   TIMESTAMPTZ
);

-- chat_message
CREATE TABLE IF NOT EXISTS chat_message (
  message_id       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  chat_room_id     UUID REFERENCES chat_room(chat_room_id) ON DELETE CASCADE,
  author_id        BIGINT REFERENCES users(user_id),
  role             VARCHAR(16) CHECK (role IN ('user', 'assistant', 'system')),
  content          TEXT NOT NULL,
  filtered_content TEXT,
  external_id      VARCHAR(64),
  created_at       TIMESTAMPTZ DEFAULT now(),
  turn_index       INT,
  CONSTRAINT uk_room_turn_role UNIQUE (chat_room_id, turn_index, role)
);

-- user_setting
CREATE TABLE IF NOT EXISTS user_setting (
  user_setting_id   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           BIGINT UNIQUE REFERENCES users(user_id),
  call_me           VARCHAR(64),
  role_description  TEXT,
  preferred_tone    preferred_tone,
  traits            TEXT,
  additional_context TEXT,
  created_at        TIMESTAMPTZ DEFAULT now(),
  updated_at        TIMESTAMPTZ
);

-- room_summary_state
CREATE TABLE IF NOT EXISTS room_summary_state (
  chat_room_id    UUID PRIMARY KEY REFERENCES chat_room(chat_room_id),
  last_turn_end   INT,
  last_summary_at TIMESTAMPTZ
);

-- user_memory_embedding
CREATE TABLE IF NOT EXISTS user_memory_embedding (
  embedding_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      BIGINT REFERENCES users(user_id),
  chat_room_id UUID REFERENCES chat_room(chat_room_id),
  source_type  VARCHAR(16) CHECK (source_type IN ('message', 'summary')),
  source_id    UUID,
  content      TEXT,
  embedding    VECTOR(1536),
  created_at   TIMESTAMPTZ DEFAULT now(),
  turn_start   INT,
  turn_end     INT
);

-- filter_result
CREATE TABLE IF NOT EXISTS filter_result (
  filter_id    BIGSERIAL PRIMARY KEY,
  chat_room_id UUID REFERENCES chat_room(chat_room_id),
  message_id   UUID REFERENCES chat_message(message_id),
  stage        VARCHAR(16) CHECK (stage IN ('rule', 'ml')),
  action       VARCHAR(8)  CHECK (action IN ('PASS', 'DROP')),
  rule_name    VARCHAR(64),
  score        NUMERIC(5,3),
  created_at   TIMESTAMPTZ DEFAULT now()
);

-- prompt_built
CREATE TABLE IF NOT EXISTS prompt_built (
  trace_id      VARCHAR(64) PRIMARY KEY,
  built_prompt  TEXT,
  context_messages JSONB,
  created_at    TIMESTAMPTZ DEFAULT now()
);

-- llm_response
CREATE TABLE IF NOT EXISTS llm_response (
  trace_id        VARCHAR(64) PRIMARY KEY,
  model_name      VARCHAR(64),
  temperature     FLOAT,
  top_p           FLOAT,
  response_text   TEXT,
  response_tokens INT,
  latency_ms      INT,
  total_cost_usd  NUMERIC(14,6),
  created_at      TIMESTAMPTZ DEFAULT now()
);

-- token_usage
CREATE TABLE IF NOT EXISTS token_usage (
    id UUID PRIMARY KEY,
    user_id UUID,
    message_id UUID,
    prompt_tokens INT,
    completion_tokens INT,
    total_tokens INT,
    cost_usd NUMERIC(14, 6),
    energy_wh NUMERIC(14, 6),
    co2_g NUMERIC(14, 6),
    saved_tokens INT,
    saved_cost_usd NUMERIC(14, 6),
    saved_energy_wh NUMERIC(14, 6),
    saved_co2_g NUMERIC(14, 6),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- message_attachment
CREATE TABLE IF NOT EXISTS message_attachment (
  attachment_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id    UUID REFERENCES chat_message(message_id),
  type          VARCHAR(32),
  url           TEXT,
  meta          JSONB,
  created_at    TIMESTAMPTZ DEFAULT now()
);

-- error_log
CREATE TABLE IF NOT EXISTS error_log (
  trace_id      VARCHAR(64) PRIMARY KEY,
  error_type    VARCHAR(32),
  error_message TEXT,
  stack_trace   TEXT,
  created_at    TIMESTAMPTZ DEFAULT now()
);

-- user_saved_token_daily
CREATE TABLE IF NOT EXISTS user_saved_token_daily (
   user_id TEXT,
   window_start TIMESTAMPTZ,
   request_count BIGINT,
   saved_tokens BIGINT,
   token_sum BIGINT,
   cost_sum_usd NUMERIC(14, 6),
   PRIMARY KEY (user_id, window_start)
);

-- global_saved_token_daily
CREATE TABLE IF NOT EXISTS global_saved_token_daily (
    window_start TIMESTAMPTZ PRIMARY KEY,
    request_count BIGINT,
    saved_tokens BIGINT,
    token_sum BIGINT,
    cost_sum_usd NUMERIC(14, 6)
);

-- user_saved_token_total
CREATE TABLE IF NOT EXISTS user_saved_token_total (
    user_id TEXT,
    stat_date TIMESTAMPTZ,
    request_count BIGINT,
    saved_tokens BIGINT,
    token_sum BIGINT,
    cost_sum_usd NUMERIC(14, 6),
    PRIMARY KEY (user_id, stat_date)
);

-- global_saved_token_total
CREATE TABLE IF NOT EXISTS global_saved_token_total (
    stat_date TIMESTAMPTZ PRIMARY KEY,
    request_count BIGINT,
    saved_tokens BIGINT,
    token_sum BIGINT,
    cost_sum_usd NUMERIC(14, 6)
);

COMMIT;
